import 'screens/screens.dart';

final widgets = {
  'AboutDialog': const AboutDialogScreen(),
  'AboutListTile': AboutListTileScreen(),
  'AbsorbPointer': const AbsorbPointerScreen(),
  'ActionChip': const ActionChipScreen(),
  'ActionIconTheme': const ActionIconThemeScreen(),
  'AdaptiveTextSelectionToolbar': const AdaptiveTextSelectionToolbarScreen(),
  'AlertDialog': const AlertDialogScreen(),
  'Align': const AlignScreen(),
  'AlignTransition': const AlignTransitionScreen(),
  'AndroidView (TODO)': const AndroidViewScreen(),
  'AndroidViewSurface (TODO)': const AndroidViewSurfaceScreen(),
  'AnimatedAlign': const AnimatedAlignScreen(),
  'AnimatedBuilder': const AnimatedBuilderScreen(),
  'AnimatedContainer': const AnimatedContainerScreen(),
  'AnimatedCrossFade': const AnimatedCrossFadeScreen(),
  'AnimatedDefaultTextStyle': const AnimatedDefaultTextStyleScreen(),
  'AnimatedFractionallySizedBox': const AnimatedFractionallySizedBoxScreen(),
  'AnimatedGridScreen(TODO)': const AnimatedGridScreen(),
  'AnimatedIconScreen': const AnimatedIconScreen(),
  'AnimatedIconScreen(TODO)': const AnimatedListScreen(),
  'AnimatedModalBarrier(TODO)': const AnimatedModalBarrierScreen(),
  'AnimatedOpacity': const AnimatedOpacityScreen(),
  'AnimatedPadding': const AnimatedPaddingScreen(),
  'AnimatedPhysicalModel': const AnimatedPhysicalModelScreen(),
  'AnimatedPositioned': const AnimatedPositionedScreen(),
  'AnimatedPositionedDirectional': const AnimatedPositionedDirectionalScreen(),
  'AnimatedRotation': const AnimatedRotationScreen(),
  'AnimatedScale': const AnimatedScaleScreen(),
  'AnimatedSize': const AnimatedSizeScreen(),
  'AnimatedSlide': const AnimatedSlideScreen(),
  'AnimatedSwitcher': const AnimatedSwitcherScreen(),
};
