import 'screens/screens.dart';

final widgets = {
  'AboutDialog': const AboutDialogScreen(),
  'AboutListTile': AboutListTileScreen(),
  'AbsorbPointer': const AbsorbPointerScreen(),
  'ActionChip': const ActionChipScreen(),
  'ActionIconTheme': const ActionIconThemeScreen(),
  'AdaptiveTextSelectionToolbar': const AdaptiveTextSelectionToolbarScreen(),
  'AlertDialog': const AlertDialogScreen(),
  'Align': const AlignScreen(),
  'AlignTransition': const AlignTransitionScreen(),
  'AndroidView (TODO)': const AndroidViewScreen(),
  'AndroidViewSurface (TODO)': const AndroidViewSurfaceScreen(),
  'AnimatedAlign': const AnimatedAlignScreen(),
  'AnimatedBuilder': const AnimatedBuilderScreen(),
  'AnimatedContainer': const AnimatedContainerScreen(),
  'AnimatedCrossFade': const AnimatedCrossFadeScreen(),
  'AnimatedDefaultTextStyle': const AnimatedDefaultTextStyleScreen(),
  'AnimatedFractionallySizedBox': const AnimatedFractionallySizedBoxScreen(),
  'AnimatedGridScreen(TODO)': const AnimatedGridScreen(),
  'AnimatedIconScreen': const AnimatedIconScreen(),
  'AnimatedIconScreen(TODO)': const AnimatedListScreen(),
  'AnimatedModalBarrier(TODO)': const AnimatedModalBarrierScreen(),
  'AnimatedOpacity(TODO)': const AnimatedOpacityScreen(),
};
